/// <reference lib="webworker" />
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'

declare let self: ServiceWorkerGlobalScope

// Cleanup old caches
cleanupOutdatedCaches()

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Handle SPA navigation
let allowlist: undefined | RegExp[]
if (import.meta.env.DEV)
    allowlist = [/^\/$/]

registerRoute(new NavigationRoute(createHandlerBoundToURL('/index.html'), { allowlist }))

// Push Event Listener
self.addEventListener('push', (event) => {
    const data = event.data ? event.data.json() : {};
    const title = data.title || 'Todo Reminder';
    const body = data.body || 'You have pending tasks.';
    const icon = '/pwa-192x192.png';
    const badge = '/mask-icon.svg';

    event.waitUntil(
        self.registration.showNotification(title, {
            body: body,
            icon: icon,
            badge: badge,
            tag: 'todo-reminder',
            data: { url: data.url || '/' }
        })
    );
});

// Notification Click Listener
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If app is open, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === '/' && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow(event.notification.data.url || '/');
            }
        })
    );
});
